In [24]:
!python analise_vendas.py

In [25]:
import pandas as pd

In [66]:
#Exibindo as 5 primeiras linhas
df = pd.read_csv("/content/vendas.csv")
df

,data,produto,categoria,quantidade,preco_unitario,cliente,regiao
0,2025-12-09,Headset G,Periféricos,1,2759,Fernanda,Sudeste
1,2025-03-12,Armário P,Móveis,2,4516,Rafael,Norte
2,2025-11-24,Mesa Escritório N,Móveis,1,4347,Rafael,Sudeste
3,2025-09-14,Tênis T,Vestuário,3,3046,Ana,Norte
4,2025-08-03,Boné V,Vestuário,2,4453,Bruno,Centro-Oeste
...,...,...,...,...,...,...,...
95,2025-02-08,Impressora I,Periféricos,3,4561,Fernanda,Nordeste
96,2025-10-16,Celular A,Eletrônicos,1,2046,Carla,Sul
97,2025-03-15,Celular A,Eletrônicos,5,4390,Carla,Nordeste
98,2025-02-07,Calça U,Vestuário,5,2472,Rafael,Norte
99,2025-05-06,Camisa R,Vestuário,4,3800,Maria,Centro-Oeste

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   data            100 non-null    object
 1   produto         100 non-null    object
 2   categoria       100 non-null    object
 3   quantidade      100 non-null    int64
 4   preco_unitario  100 non-null    int64
 5   cliente         100 non-null    object
 6   regiao          100 non-null    object
dtypes: int64(2), object(5)
memory usage: 5.6+ KB

In [68]:
df.head()

,data,produto,categoria,quantidade,preco_unitario,cliente,regiao
0,2025-12-09,Headset G,Periféricos,1,2759,Fernanda,Sudeste
1,2025-03-12,Armário P,Móveis,2,4516,Rafael,Norte
2,2025-11-24,Mesa Escritório N,Móveis,1,4347,Rafael,Sudeste
3,2025-09-14,Tênis T,Vestuário,3,3046,Ana,Norte
4,2025-08-03,Boné V,Vestuário,2,4453,Bruno,Centro-Oeste

In [35]:
#Número totao de linhas e colunas
df.shape

(100, 7)

In [69]:
#Calculando receita total
df["receita_total"] = df["quantidade"] * df["preco_unitario"]
df["receita_total"]

0      2759
1      9032
2      4347
3      9138
4      8906
      ...
95    13683
96     2046
97    21950
98    12360
99    15200
Name: receita_total, Length: 100, dtype: int64

In [50]:
#Filtrando e exibindo as vendas da categoria Eletrônicos
df_eletronicos = df.loc[df["categoria"] == "Eletrônicos"]
df_eletronicos

,data,produto,categoria,quantidade,preco_unitario,cliente,regiao,receita_total
5,2025-07-24,Tablet D,Eletrônicos,2,4893,Fernanda,Sudeste,9786
6,2025-05-20,Monitor B,Eletrônicos,1,3060,Lucas,Sul,3060
9,2025-06-01,Celular A,Eletrônicos,3,516,João,Centro-Oeste,1548
10,2025-04-22,Celular A,Eletrônicos,2,1018,Fernanda,Nordeste,2036
13,2025-11-24,Notebook X,Eletrônicos,1,2670,Ana,Sul,2670
14,2025-05-30,Tablet D,Eletrônicos,4,2575,Maria,Nordeste,10300
15,2025-09-19,Notebook X,Eletrônicos,2,2778,Rafael,Norte,5556
27,2025-01-30,Notebook X,Eletrônicos,5,1006,Lucas,Sudeste,5030
32,2025-07-07,Tablet D,Eletrônicos,2,2533,Camila,Sul,5066
33,2025-11-20,Notebook X,Eletrônicos,4,3998,Pedro,Nordeste,15992
36,2025-08-01,Fone C,Eletrônicos,5,2433,Pedro,Sul,12165
41,2025-08-06,Fone C,Eletrônicos,5,246,Rafael,Sudeste,1230
44,2025-05-25,Monitor B,Eletrônicos,2,3607,Lucas,Sul,7214
49,2025-07-05,Fone C,Eletrônicos,4,2864,Fernanda,Sudeste,11456
54,2025-04-01,Fone C,Eletrônicos,2,4350,Lucas,Centro-Oeste,8700
55,2025-04-09,Celular A,Eletrônicos,3,4362,Pedro,Norte,13086
60,2025-10-05,Celular A,Eletrônicos,2,2742,Pedro,Norte,5484
62,2025-11-29,Fone C,Eletrônicos,5,2798,Lucas,Norte,13990
71,2025-10-12,Tablet D,Eletrônicos,2,4147,João,Sul,8294
73,2025-08-15,Monitor B,Eletrônicos,5,3644,Pedro,Sudeste,18220
76,2025-03-19,Celular A,Eletrônicos,5,922,Lucas,Sul,4610
80,2025-03-16,Notebook X,Eletrônicos,3,4518,Rafael,Sul,13554
83,2025-11-13,Fone C,Eletrônicos,5,4939,Rafael,Centro-Oeste,24695
85,2025-03-18,Notebook X,Eletrônicos,1,4603,Ana,Centro-Oeste,4603
90,2025-08-26,Monitor B,Eletrônicos,2,2718,Carla,Sudeste,5436
91,2025-01-04,Notebook X,Eletrônicos,1,1612,Pedro,Nordeste,1612
96,2025-10-16,Celular A,Eletrônicos,1,2046,Carla,Sul,2046
97,2025-03-15,Celular A,Eletrônicos,5,4390,Carla,Nordeste,21950

In [70]:
#Produto mais vendido em quantidade
produto_mais_vendido = df.groupby("produto")[["quantidade"]].sum().sort_values(by="quantidade", ascending=False).head(1).reset_index()
produto_mais_vendido

  produto  quantidade
0  Sofá Q          30

In [73]:
#Identificando a região com maior valor de compra
df_regiao = df.groupby("regiao")[["receita_total"]].sum().sort_values(by="receita_total", ascending=False).head(1).reset_index()
df_regiao

    regiao  receita_total
0  Sudeste         245605